# Hyperliquid Trading System Configuration

# Default environment (mainnet or testnet)
default_environment: testnet

# Mainnet Configuration
mainnet:
  account_address: "0xB6001dDB4ecf684A226361812476f731CEA96d05"
  api_wallet_address: "0xBa6c2972Dc5C2AA389000fbf66ac9f043E535066"
  secret_key: "0x0ff43126e90bd4fb1e06c3dff636337530ad285b40c57d215e124e6fd8e5703c"
  keystore_path: ""  # Optional: path to keystore file instead of secret_key
  base_url: null  # Will use mainnet default


# Testnet Configuration  
testnet:
  account_address: "0xB6001dDB4ecf684A226361812476f731CEA96d05"
  api_wallet_address: "0xBa6c2972Dc5C2AA389000fbf66ac9f043E535066"
  secret_key: "0x09a140d8da125158090e370213f79709c07e29454dd2e121687b3503ad0729ef"
  keystore_path: ""  # Optional: path to keystore file instead of secret_key
  base_url: "https://api.hyperliquid-testnet.xyz"
